Repository Google-Developer-Student-Club-RJIT/Donaate, pull requests merged in 2022-10, with the labels that each got.

#7 added new changes
  Donaate-UI/Images/Hero Image.png
  Donaate-UI/Slider 3.png
  Donaate-UI/hero.png
  images/banner.png
  images/donate1.png
  images/poor.png
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#14 Feature: Added footer in the website
  index.html
Labels: hacktoberfest-accepted

#10 Completed Hero Section
  Donaate-UI/MAZIUSREVIEW20.09-Italic.otf
  Donaate-UI/Vector.png
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#18 Minor fixes
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#20 Minor changes
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#21 added about section
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#24 footer changes made
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#23 added contact page
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#26 Horizontal scrolling removed
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#38 FAQ section done
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#37 Add functionality in navbar and donate button
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#46 Made navbar sticky
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#41 Donate Here Section
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#47 Updated CONTRIBUTING.md and README.md
  CONTRIBUTING.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#52 gdsc issue
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#60 Added Favicon
  Donaate-UI/Favicon.png
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#69 Changed Donate Section
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#70 Donate section
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#79 [Feature] :: Added jump to top of the page feature
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#80 Smooth scroll
  style.css
Labels: hacktoberfest-accepted, hacktoberfest
